// Central type definitions — mirrors the Firestore schema described in DESIGN.md.
// IMPORTANT: fields marked "server-only" must never be set from client code.
// Firestore security rules (see /firestore/firestore.rules) enforce this too —
// the type comments are documentation, not the enforcement mechanism.

export type UserRole = "user" | "admin";

export interface AppUser {
  uid: string;
  email: string;
  displayName: string;
  phone?: string;
  role: UserRole;
  createdAt: number; // epoch ms
}

export type CompetitionStatus = "draft" | "active" | "closed" | "winner_announced";

export interface Competition {
  id: string;
  title: string;
  description: string;
  carModel: string;
  images: string[]; // Firebase Storage URLs
  entryFeeCents: number; // e.g. 10000 = R100.00
  closingAt: number; // epoch ms
  status: CompetitionStatus;
  rulesText: string;
  /**
   * Legal note: whether a free/no-purchase entry route exists is pending
   * South African legal review (CPA s36 / Lotteries Act). This field is
   * intentionally flexible so the schema doesn't need to change once
   * that decision is made.
   */
  freeEntryMethod: "postal" | "sms" | null;
  createdBy: string; // admin uid
  updatedAt: number;
}

export type EntryStatus = "pending" | "paid" | "failed" | "cancelled" | "refunded";
export type EntryMethod = "paid" | "free_postal" | "free_sms";

export interface Entry {
  id: string;
  userId: string;
  competitionId: string;
  /** server-only: generated by Cloud Function on payment confirmation */
  referenceNumber: string | null;
  status: EntryStatus;
  entryMethod: EntryMethod;
  paymentId: string | null;
  createdAt: number;
  /** server-only */
  paidAt: number | null;
}

export type PaymentStatus = "initiated" | "succeeded" | "failed" | "cancelled";

export interface Payment {
  id: string;
  userId: string;
  entryId: string;
  competitionId: string;
  provider: "yoco" | string;
  providerChargeId: string | null;
  amountCents: number;
  currency: "ZAR";
  status: PaymentStatus;
  /** server-only: set only by the verified webhook handler */
  webhookVerifiedAt: number | null;
  createdAt: number;
}

export interface Winner {
  competitionId: string;
  entryId: string;
  displayName: string; // POPIA: show a display name/initials, not full personal data, unless winner consents
  announcedAt: number;
  prizeDescription: string;
  proofOfDrawUrl?: string;
}

export interface Faq {
  id: string;
  question: string;
  answer: string;
  order: number;
  published: boolean;
}

export interface AuditLogEntry {
  id: string;
  adminUid: string;
  action: string;
  targetId: string;
  timestamp: number;
  details?: Record<string, unknown>;
}
